server:
  port: 8080

logging:
  file:
    path: logs

  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  output:
    ansi:
      enabled: always

  jackson:
    default-property-inclusion: non_null

  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:mysql://3.37.227.119:3306/ikoDB?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true
    username: iko
    password: ikoiko!
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    jwt:
      header: Authorization
      secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
      token-validity-in-seconds: 86400